### ISSUE TITLE
The 'override' option is not working, it still run the prev command 

### ISSUE THREAD

**Issue by phucsang0spt** [Shubham-Kumar-2000/protocol-registry#12]

**Comment by Shubham-Kumar-2000** [comment]
@phucsang0spt  which operating system you are on?

**Comment by Shubham-Kumar-2000** [comment]
I am guessing this issue has been in macos. 

If yes then you can change the default app from your settings 

We are still looking to change default apps in macos in command line but no fruitful result yet

PR is welcomed.

**Comment by Shubham-Kumar-2000** [comment]
I have tested your issue and found that override works fine if the previous command was created using this package but fails if the default app is a external application

**Comment by Shubham-Kumar-2000** [comment]
Closing due to lack of evidence and response.
