### ISSUE TITLE
shelljs throw issue

### ISSUE THREAD

**Issue by jongsun89** [Shubham-Kumar-2000/protocol-registry#25]
Hi, i'm trying to use protocol-registry on vscode extension .
shelljs.exec on your lib returns null..
I debug it and config.execPath in shelljs set 'null' .
as i know vscode is electron base .. and shelljs has issue about it. 
https://github.com/shelljs/shelljs/wiki/Electron-compatibility
Any update for this ?

**Comment by Shubham-Kumar-2000** [comment]
can yo share any code snippet

**Comment by jongsun89** [comment]
it gets thrown in require .
const ProtocolRegistry = require("protocol-registry");
protocol-registry looks using shelljs only in linux, macos.
so, i do register protocol manually(not using your lib) in linux, macos cases .
Thanks.

**Comment by Shubham-Kumar-2000** [comment]
Ok, that's great to hear that you problem has been solved.

But I think if shelljs is creating problems then lets replace it with child process. Thus will be opening a new issue for removing shelljs.

Contribution is highly encouraged.

**Comment by Shubham-Kumar-2000** [comment]
Fixed with : cb27941fe3321edf9a802fab7c2f8c51700ba953
