### ISSUE TITLE
Remove Shelljs

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [Shubham-Kumar-2000/protocol-registry#26]
### **Describe the bug:**

Shelljs prevents proper functioning in electron.

### **To Reproduce:**

1. Go to a electron project.
2. Import protocol-registry

**Note:**

-   For this issue we will be removing shelljs as a dependency.

**Comment by adammartiska** [comment]
Is this issue being solved? I want to use this package, but will need to get it work also with electron app.

**Comment by Shubham-Kumar-2000** [comment]
I guess it will be finished by this week.

Progress is being made.
Contributions is highly appreciated.

**Comment by Shubham-Kumar-2000** [comment]
Fixed with : cb27941fe3321edf9a802fab7c2f8c51700ba953
