### ISSUE TITLE
Problem with spaces in path to script.sh

### ISSUE THREAD

**Issue by Vuenc** [Shubham-Kumar-2000/protocol-registry#29]
### **Describe the bug:**

I'm on linux and the script I run for registering a protocol is on a path with a space in it. I get the following error:
```
Error: chmod: cannot access '/home/vuenc/Some': No such file or directory
chmod: cannot access 'Folder/node_modules/protocol-registry/temp/script.sh': No such file or directory

    at Object.register (/home/vuenc/Some Folder/node_modules/protocol-registry/src/linux/index.js:93:52)
```
The problem is that in `src/linux/index.js` in line 92, `const chmod = await shell.exec('chmod +x ' + scriptFilePath);`, the path is passed to the shell without escaping spaces.

### **To Reproduce:**

1. Create a directory "Some Folder" in your home directory and run `npm install protocol-registry` in it
2. Create a file registerMyProtocol.js with the contents:
```js
const ProtocolRegistry = require("protocol-registry");

ProtocolRegistry.register({
    protocol: "testprotocol", // sets protocol for your command , testproto://**
    command: "echo $_URL_", // this will be executed with a extra argument %url from which it was initiated
    override: true, // Use this with caution as it will destroy all previous Registrations on this protocol
    terminal: false, // Use this to run your command inside a terminal
    script: false,
})
.catch((e) => {console.log(e)})
```
3. Run `node registerMyProtocol.js`

**Comment by Shubham-Kumar-2000** [comment]
Will fix this asap.

**Comment by Shubham-Kumar-2000** [comment]
Fixed by b4ccb0f7102879947e116ae8a084016e303e09b3

**Comment by Vuenc** [comment]
Thanks!

**Comment by Shubham-Kumar-2000** [comment]
Still waiting for test results. Will close the issue once its published

**Comment by Vuenc** [comment]
oh, sorry

**Comment by Shubham-Kumar-2000** [comment]
Publish new version 1.3.15
