### ISSUE TITLE
Let us name the wrapper file.

### ISSUE THREAD

**Issue by MistakingManx** [Shubham-Kumar-2000/protocol-registry#35]
### **Feature request**:

Instead of automatically naming it {protocol}Wrapper.(bat/sh), let us choose a name for it.

### **Describe alternatives you've considered**:

I've considered just forking your package to make this change myself, but my application automatically downloads packages from NPM when a new one is required or one goes missing, which would cause issues.

### **Describe how this feature will be useful to our users**:

It wouldn't look bad when you use the feature.

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Shubham-Kumar-2000** [comment]
Hi, 
That's a great Idea but I think lets not in force this.

Better to have ` {protocol}Wrapper.(bat/sh)` by default and allow users to over ride it.

But then we will have a problem of overlapping names of different scripts. We will have to keep this also in mind.

**Comment by Shubham-Kumar-2000** [comment]
Lets have it as `{protocol}/{protocol}Wrapper.(bat/sh)` by default
And  `{protocol}/{wrapperName}.(bat/sh)` if `wrapperName` is Provided.

Do let me know what do you think about this and we can plan a release.

**Comment by MistakingManx** [comment]
Sorry for the extremely late reply, but why would we want the wrapper part at all?
As long as removing it is an option, I don't mind however you implement it.

If you really want, you can make it so that wrapperName (if type is not a string) default to "Wrapper".

**Comment by Shubham-Kumar-2000** [comment]
Ok will remove it `wrapper` we can simply have `{protocol}/{protocol}.(bat/sh)`.

Will test and release this by end of this month.

**Comment by Shubham-Kumar-2000** [comment]
This has been fixed in `v1.4.0`
