### ISSUE TITLE
Absolute Path of Command is Required on MacOS when Terminal Mode is Off

### ISSUE THREAD

**Issue by Grayseon** [Shubham-Kumar-2000/protocol-registry#47]
### **Describe the bug:**

On MacOS systems, (as mentioned in the bottom of the README) an absolute path is required to run commands when terminal mode is off.

### **To Reproduce:**

1. Set the `command` to use a non built-in command, such as `"node ${path.join(__dirname, './tester.js')} $_URL_"` (See how it uses node?)
2. Set `terminal` to `false` in the configuration.
3. Register the protocol.
4. Go to the protocol in a browser.
5. It will error and say that the command does not exist.

### **Expected behavior:**

It should run the command like a user is doing so.

<hr/>

**Comment by Shubham-Kumar-2000** [comment]
Please fix requested changes

**Comment by Shubham-Kumar-2000** [comment]
This is fixed and released.
